name: simba_dev
channels:
  - defaults
dependencies:
  - python=3.6
  - shapely
  - matplotlib
  - statsmodels
  - wxpython
  - hdbscan==0.8.27
  - pip:
      - pip==21.2.2
      - sphinx-autodoc-typehints
      - sphinxcontrib-video
      - sphinx-togglebutton==0.3.2
      - sphinx_rtd_theme
      - simba-uw-tf-dev
      - nbsphinx
      - umap-learn==0.5.2
      - pyvis==0.3.2
prefix: /Users/simon/.conda/envs/simba_dev
